name: device_info_fetcher
description: A starting point for Dart libraries or applications.
version: 1.0.1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_info_plus:
  pax_api_plugin:
    git:
      url: https://github.com/Flutter-Apps-pty/pax_api_plugin.git
#  flutter_test:
#    sdk: flutter
#  test: ^1.21.0
#  integration_test:
#    sdk: flutter
#  flutter_lints: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0