name: device_info_fetcher
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  device_info_plus:
  pax_api_plugin:

dependency_overrides:
  pax_api_plugin:
    git:
      url: https://github.com/Flutter-Apps-pty/pax_api_plugin
    
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
