name: device_info_fetcher
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: '>=3.1.6 <4.0.0'

dependencies:
  device_info_plus:
  uuid:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
