name: device_info_fetcher
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter_device_identifier:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
